language: node_js
cache: yarn
node_js:
  - "node"
  - "10"
  - "lts/*"

before_script:
  - yarn run setup
script:
  # Build all packages
  - yarn run build
  # Lint all packages
  - yarn run lint
  # Run tests and coverage
  - yarn run cover
after_success:
  # Upload coverage data
  - c8 report --reporter=text-lcov | coveralls

before_deploy:
  - openssl aes-256-cbc -K $encrypted_226d8df99612_key -iv $encrypted_226d8df99612_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
addons:
  ssh_known_hosts:
    - uiengine.uix.space
    - uiengine-sample-project.uix.space
deploy:
  # Deploy doc site
  - provider: script
    skip_cleanup: true
    script: yarn run docs:deploy
    on:
      branch: master
      node: "10"
  # Deploy test project
  - provider: script
    skip_cleanup: true
    script: yarn run test-project:deploy
    on:
      branch: master
      node: "10"
after_deploy:
  - yarn run docs:lighthouse
  - yarn run docs:deploy_lighthouse
